using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Avalonia;

namespace Insait_Edit_C_Sharp.Services;

/// <summary>
/// Manages user-created custom translation dictionaries.
///
/// Each custom language is stored as an AXAML ResourceDictionary file in:
///   %AppData%\InsaitEdit\CustomTranslations\{LanguageName}.axaml
///
/// The dictionary is generated by Gemini (see <see cref="GeminiService"/>)
/// and its key-value pairs are loaded into <see cref="Application.Current.Resources"/> on demand.
/// </summary>
public static class CustomTranslationService
{
    private static readonly string _translationsDir;

    // Currently loaded custom strings: key → value
    private static System.Collections.Generic.Dictionary<string, string>? _loadedEntries;
    private static string? _loadedLanguageName;

    static CustomTranslationService()
    {
        _translationsDir = Path.Combine(SettingsDbService.AppDataDir, "CustomTranslations");
        Directory.CreateDirectory(_translationsDir);
    }

    /// <summary>AppData folder where custom AXAML dictionaries are stored.</summary>
    public static string TranslationsDirectory => _translationsDir;

    /// <summary>
    /// Returns the path to the AXAML file for the given language name.
    /// The file may not exist yet.
    /// </summary>
    public static string GetDictionaryPath(string languageName)
        => Path.Combine(_translationsDir, $"{SanitizeName(languageName)}.axaml");

    /// <summary>
    /// Returns whether a local AXAML dictionary already exists for this language.
    /// </summary>
    public static bool DictionaryExists(string languageName)
        => File.Exists(GetDictionaryPath(languageName));

    /// <summary>
    /// Generates (or regenerates) the custom AXAML translation for
    /// <paramref name="languageName"/> using Gemini and the supplied
    /// <paramref name="model"/>, then saves it to AppData.
    /// </summary>
    public static async Task<string> GenerateAndSaveAsync(
        string languageName,
        string model,
        Action<string>? onProgress = null,
        CancellationToken ct = default)
    {
        onProgress?.Invoke("Reading English dictionary…");

        // Load the built-in English AXAML as the source
        string englishContent;
        try
        {
            englishContent = await LoadEnglishAxamlAsync(ct);
        }
        catch (Exception ex)
        {
            return $"Error reading English.axaml: {ex.Message}";
        }

        onProgress?.Invoke($"Translating to {languageName} via Gemini ({model})…");

        var translated = await GeminiService.TranslateAxamlAsync(
            model, languageName, englishContent, ct);

        if (translated.StartsWith("Error:"))
            return translated;

        // Strip any markdown code fences Gemini might have added
        translated = StripMarkdown(translated);

        // Validate that it looks like AXAML
        if (!translated.TrimStart().StartsWith("<"))
            return $"Error: Gemini did not return valid AXAML. Response: {translated[..Math.Min(300, translated.Length)]}";

        onProgress?.Invoke("Saving translation file…");

        var path = GetDictionaryPath(languageName);
        try
        {
            await File.WriteAllTextAsync(path, translated, System.Text.Encoding.UTF8, ct);
        }
        catch (Exception ex)
        {
            return $"Error saving file: {ex.Message}";
        }

        onProgress?.Invoke("Done.");
        return path;
    }

    /// <summary>
    /// Loads the custom AXAML dictionary for the given language.
    /// Parses the AXAML file and injects all x:String entries directly into
    /// <see cref="Application.Current.Resources"/> so that
    /// <see cref="LocalizationService.Get"/> can find them.
    /// </summary>
    public static void LoadCustomDictionary(string languageName)
    {
        var path = GetDictionaryPath(languageName);
        if (!File.Exists(path)) return;

        var app = Application.Current;
        if (app == null) return;

        // Unload any previously loaded custom entries
        UnloadCustomDictionary();

        try
        {
            var xmlContent = File.ReadAllText(path);
            var entries = ParseAxamlStrings(xmlContent);
            _loadedEntries = entries;
            _loadedLanguageName = languageName;

            // Inject entries into Application.Current.Resources
            foreach (var kv in entries)
                app.Resources[kv.Key] = kv.Value;

            System.Diagnostics.Debug.WriteLine(
                $"[CustomTranslation] Loaded {entries.Count} entries for '{languageName}'");
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine(
                $"[CustomTranslation] Failed to load {path}: {ex.Message}");
        }
    }

    /// <summary>Unloads the currently active custom dictionary if any.</summary>
    public static void UnloadCustomDictionary()
    {
        var app = Application.Current;
        if (app == null || _loadedEntries == null) return;

        // Remove our injected keys from Application resources
        foreach (var key in _loadedEntries.Keys)
        {
            // Only remove if our value is still there (don't overwrite a built-in key that was restored)
            if (app.Resources.TryGetResource(key, null, out var existing) &&
                existing is string s && s == _loadedEntries[key])
            {
                app.Resources.Remove(key);
            }
        }

        _loadedEntries = null;
        _loadedLanguageName = null;
    }

    // ── helpers ──────────────────────────────────────────────────────────

    /// <summary>
    /// Parses x:String entries from an AXAML ResourceDictionary using simple regex.
    /// </summary>
    private static System.Collections.Generic.Dictionary<string, string> ParseAxamlStrings(string xml)
    {
        var result = new System.Collections.Generic.Dictionary<string, string>();
        // Match <x:String x:Key="SomeKey">Some Value</x:String>
        var rx = new System.Text.RegularExpressions.Regex(
            @"<x:String\s+x:Key=""([^""]+)""[^>]*>([^<]*)</x:String>",
            System.Text.RegularExpressions.RegexOptions.Compiled);
        foreach (System.Text.RegularExpressions.Match m in rx.Matches(xml))
        {
            var key = m.Groups[1].Value;
            var val = System.Net.WebUtility.HtmlDecode(m.Groups[2].Value);
            result[key] = val;
        }
        return result;
    }

    /// <summary>
    /// Reads the English.axaml source file.
    /// Tries Avalonia's asset loader first; falls back to reading the file from disk
    /// (relative to the application executable) if the asset is not embedded.
    /// </summary>
    private static async Task<string> LoadEnglishAxamlAsync(CancellationToken ct)
    {
        // 1) Try avares:// — the space in the folder name must be percent-encoded in the path segment too
        try
        {
            var uri = new Uri("avares://Insait%20Edit%20C%20Sharp/Interface%20Localization/English.axaml");
            using var stream = Avalonia.Platform.AssetLoader.Open(uri);
            using var reader = new StreamReader(stream);
            return await reader.ReadToEndAsync(ct);
        }
        catch { /* fall through to disk fallback */ }

        // 2) Fallback: read from disk next to the running exe
        var baseDir = AppContext.BaseDirectory;
        var candidates = new[]
        {
            Path.Combine(baseDir, "Interface Localization", "English.axaml"),
            Path.Combine(baseDir, "..", "Interface Localization", "English.axaml"),
            // development layout: source folder
            Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "Insait Edit C Sharp", "Interface Localization", "English.axaml"),
        };

        foreach (var candidate in candidates)
        {
            var full = Path.GetFullPath(candidate);
            if (File.Exists(full))
                return await File.ReadAllTextAsync(full, System.Text.Encoding.UTF8, ct);
        }

        throw new FileNotFoundException(
            "English.axaml not found via asset loader or disk fallback.");
    }

    private static string SanitizeName(string name)
    {
        foreach (var c in Path.GetInvalidFileNameChars())
            name = name.Replace(c, '_');
        return name;
    }

    private static string StripMarkdown(string text)
    {
        text = text.Trim();
        if (text.StartsWith("```xml"))       text = text[6..].Trim();
        else if (text.StartsWith("```"))     text = text[3..].Trim();
        if (text.EndsWith("```"))            text = text[..^3].Trim();
        return text;
    }
}

